Dev account
candy-devs/candy-server-spring pull request #4
Opened 2022-07-21 11:38 UTC by JJONSOO

- [O] 1. Account Entity 
 - [O ] 2. Account Service 
 - [O] 3. Account Controller
 - [O] 4. Account Send Test
 - [O] 5. Transaction Entity
 - [O] 6. Error Exception

2022-07-21 13:27 UTC, rollrat commented on src/main/java/candy/server/domain/account/dto/AccountSendRequestDto.java
> +    private Long accountSenderId;
userSpecific으로 받아야합니다.

2022-07-21 14:44 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/dto/AccountSendRequestDto.java
> +    private Long accountSenderId;
바꿨습니다.

2022-07-22 03:00 UTC, rollrat commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        if(sender.get().getAccountUserCandyCnt()-dto.getAccountCandyCnt()<0||sender.get().getAccountUserCandyCnt()==0){
`sender.get().getAccountUserCandyCnt()` 부분이 중복되니깐 변수로 빼는 게 좋을 것 같아요

2022-07-22 03:00 UTC, rollrat commented on src/main/java/candy/server/domain/account/dto/AccountSendRequestDto.java
> +    private String accountSenderSpecificId;
dto는 항상 최소 정보만 있어야합니다.
sender의 `userId`는 `RestController`에서 `@LoginUser`로 가져올 수 있기 때문에 필요없어요
errorMessage는 ResponseDto에 있어야 해요
그리고 Dto의 변수 명은 최대한 짧게 해주세요
`accountCandyCnt => value or count`
`accountReceiverSpecificId => receiver or target`

2022-07-22 07:10 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        if(sender.get().getAccountUserCandyCnt()-dto.getAccountCandyCnt()<0||sender.get().getAccountUserCandyCnt()==0){
sender count , receiver count 둘 다 변수로 빼서 사용하였습니다.

2022-07-22 07:11 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/dto/AccountSendRequestDto.java
> +    private String accountSenderSpecificId;
AccountReponseDto 새로 만들어서 errorMessage 넣어주고
AccoundSendRequestDto accountSenderSpecificId 바꿔주고
변수명을 accountCandyCnt -> count , accountReceiverSpecificId -> receiver 로 바꿔주었습니다.

2022-07-22 12:25 UTC, rollrat requested changes

2022-07-22 12:25 UTC, rollrat commented on src/main/java/candy/server/domain/account/entity/CaAccountEntity.java
> +    private CaUserEntity caUserEntity;
caUserEntity의 JoinColumn은 userSpecificId가 아니라 userId여야 합니다.
userSpecificId는 중복될 일은 없지만, 언제든지 바뀔 수 있기 때문에 CaAccount의 무결성이 깨질 수 있습니다.

2022-07-22 12:25 UTC, rollrat commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        Optional<CaAccountEntity> sender = accountRepository.findByCaUserEntityUserNickname(user.getName());
위 코멘트랑 이어지는 내용입니다.
```java
accountRepository.findByUserId(user.getId());
```
로 바꾸면 될 것 같네요

2022-07-22 12:34 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        Optional<CaAccountEntity> sender = accountRepository.findByCaUserEntityUserNickname(user.getName());
넵 확인했습니다.
몇가지 질문이 있는데요.
나머지 Task 중 Transaction Entity save 하는 부분을 SendCandy 함수 내에서 선언해야할까요 아니면 함수를 따로 만들어 SendCandy -> SaveTranscatoin 이런식으로 함수를 한번 더 타고 들어가게 구현해야할까요?
다른 질문은 현재 Receiver가 존재하지 않을 때 Try catch 문으로 오류 처리를 하였는데 현준님께서 구현하신 enum을 사용해서 처리를 해야할까요? 코드의 간결성 때문에 질문합니다.

2022-07-22 13:23 UTC, rollrat commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        Optional<CaAccountEntity> sender = accountRepository.findByCaUserEntityUserNickname(user.getName());
try-catch를 쓰셔도 되긴하지만, try-catch는 내부적으로 execption 오브젝트 생성 시간때문에 오버헤드가 커요
그래서 보통 try-catch는 최소한으로 사용하고, enum이나 string으로 처리할 수 있으면 그렇게 하는게 좋다고 해요
 
sendCandy 로직에 transaction생성 로직이 포함되어 있다고 생각할 수 있으니깐 따로 메서드 분리없이 하나의 메서드에서 전부 처리해도 괜찮을 것 같네요
원하는 대로 하면 될 것 같아요

2022-07-23 06:22 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        Optional<CaAccountEntity> sender = accountRepository.findByCaUserEntityUserNickname(user.getName());
말씀하신대로
try -catch 문 -> isEmpty 으로 교체
transaction 생성을 sendycandy 메서드 안에서 진행하도록 구현하고 테스트 완료하였습니다.

2022-07-23 08:22 UTC, rollrat requested changes

2022-07-23 08:22 UTC, rollrat commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        System.out.println(receiver.get().getAccountCount());
이 부분만 삭제해주시면 커밋할께요
고생하셨어요!

2022-07-23 08:24 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/service/AccountSendService.java
> +        System.out.println(receiver.get().getAccountCount());
삭제 했습니다!

2022-07-23 09:41 UTC, rollrat requested changes

2022-07-23 09:41 UTC, rollrat commented on src/main/java/candy/server/domain/account/entity/CaTransactionEntity.java
> +    private Long CandyCnt;
이거 prefix 소문자로 해주세요

2022-07-23 11:43 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/entity/CaTransactionEntity.java
> +    private Long CandyCnt;
소문자로 바꿨습니다

2022-07-23 12:28 UTC, rollrat commented on src/main/java/candy/server/domain/account/entity/CaTransactionEntity.java
> +    private Long CandyCnt;
테스트 코드에 builder() 도 바꿔야 되요

2022-07-23 14:15 UTC, JJONSOO commented on src/main/java/candy/server/domain/account/entity/CaTransactionEntity.java
> +    private Long CandyCnt;
테스트 코드 중 정확히 어떤 부분인지 알 수 있을까요?

2022-07-23 23:45 UTC, rollrat commented on src/main/java/candy/server/domain/account/entity/CaTransactionEntity.java
> +    private Long CandyCnt;
다 고쳐진거 같네요

2022-07-23 23:45 UTC, rollrat approved these changes

2022-07-23 23:46 UTC, merged